### ISSUE TITLE
Balance incorrect in wallet

### ISSUE THREAD

**Issue by Bastijn** [Bastijn/g-dash#1]
Incorrect balance for a specific account is shown when a transaction is created (sent) and unconfirmed. After confirmation of the transaction (6 confirmations) the balance is correct. The total balance of all accounts does show the correct amount.

**Comment by mjmacleod** [comment]
Thanks for the report. Via which RPC command is this?

I believe it is possible this has already been fixed in the dev branch, but lets keep this bug open and double check during final 2.0 testing.

**Comment by Bastijn** [comment]
I use the "getbalance" RPC command for this.

For the total amount in the wallet (for all accounts) "getbalance" is used without arguments. For a specific account, "getbalance" is used with the argument "account" (UUID). I know bitcoind has a second argument "minconf" with a default value of "1". I did not check if this second argument can also be passed to GuldenD and what the default value is. I will keep this bug open and check this again with 2.0.
