### ISSUE TITLE
Make it more clear to people not to change their RPC Password

### ISSUE THREAD

**Issue by SandroLorenz** [Bastijn/g-dash#13]
Make it more clear that everything is already set right by default, by using red letters for example, which also makes clear not to change anything in the Gulden settings tab unless they really need to and know what they are doing.

**Comment by Bastijn** [comment]
Added a textual warning for this in commit https://github.com/Bastijn/g-dash/commit/7cf2a7cb9472b2b0379f772c6c5718546ee9440c
