### ISSUE TITLE
Witness account info doesn't expand on some accounts

### ISSUE THREAD

**Issue by orobio** [Bastijn/g-dash#15]
I have 4 imported witness accounts, of which 2 are new accounts imported yesterday and the other 2 have been running for a while. When clicking the basic witness account information, it expands to show more detailed information. However, this only works for the 2 accounts that have been running for a while. The 2 new accounts do not respond at all to a click. Only thing that does work is the tooltip that appears when hovering above the arrows: "Click to expand for more info".

I tried turning it off and on again.

Hardware: Raspberry Pi
Gulden version: 2000011
G-Dash version: 1.1

Same results with Safari on iOS, macOS, and Firefox on Linux.

In case it has something to do with the names of the witness accounts. The 2 working account names only consist of letters and an underscore. The 2 non-working account names consist of letters, numbers and a dot.

**Comment by Bastijn** [comment]
Hi Orobio, thanks for reporting the issue. Could you try to rename the witness accounts that have a dot in the name and replace that with for example an "x" or a zero? Thanks.

**Comment by orobio** [comment]
Yes of course, I could've tried that already! I just thought of the name difference when I was already writing the issue.

I replaced the dot with an underscore and that fixes the problem.

**Comment by Bastijn** [comment]
Great. Good to know that fixed the issue. I'll add something in the future that will replace dots for account names that contain a dot with something else.

**Comment by Bastijn** [comment]
Fixed in commit a7444e7fddafeba9fdd26689e6be4195a0329ce6
