### ISSUE TITLE
v0.22 - Password Format - Not enforcing complex password

### ISSUE THREAD

**Issue by EyePeaSea** [Bastijn/g-dash#2]
The requirement for at least uppercase letter and 1 number is not enforced in the password check.

**Comment by mjmacleod** [comment]
To my understanding, there is pretty common consensus in the security community at this point in time that password restrictions like the above are bad practice.

While not a scientific article take e.g. https://gizmodo.com/the-guy-who-invented-those-annoying-password-rules-now-1797643987 as an example.

It is therefore unlikely that we are going to enforce password restrictions of any kind, if we do it will be length of password (which is the only thing that really matters) and/or to encourage people to use pass phrases instead.

**Comment by mjmacleod** [comment]
Possibly consider enforcing password length rules instead and drop uppercase/number etc. requirements entirely, the latter are no longer really considered a great idea - see e.g. https://gizmodo.com/the-guy-who-invented-those-annoying-password-rules-now-1797643987 for a bit more discussion on this.

**Comment by Bastijn** [comment]
Thanks for reporting! I agree with Malcolm, and I will remove the check for uppercase/numbers and only enforce the length (I still love this example: https://xkcd.com/936/).

**Comment by Bastijn** [comment]
Fixed in version 0.23
