### ISSUE TITLE
IP-location only for inbound connections

### ISSUE THREAD

**Issue by FornaxNLG** [Bastijn/g-dash#20]
Node info gives information about the number of outbound and inbound connections, it also give a nice indication of their origins, split out per country and per city.
It only gives location info for inbound connections, it totaly ignores outbound connections.

![afbeelding](https://user-images.githubusercontent.com/35969914/63640165-5503fa80-c69d-11e9-85b5-5184334e8ec9.png)

**Comment by Bastijn** [comment]
Fixed in https://github.com/Bastijn/g-dash/commit/dd3c605bc17a164ee90da9e5d39ca089011a4927
