### ISSUE TITLE
Setting password for unencrypted existing wallet behaves erratically.

### ISSUE THREAD

**Issue by FornaxNLG** [Bastijn/g-dash#21]
I transplanted a wallet.dat from elsewhere. 
G-Dash noticed it was not encrypted so I made use of the offer to set a password. 
Now G-Dash stopped GuldenD, shredded this existing (not empty!) wallet.dat and created a new empty one.

http://<ip-address>/?page=wallet#setuppassphrase

![afbeelding](https://user-images.githubusercontent.com/35969914/63641674-a10d6a00-c6b2-11e9-9ebb-996e0a7369ca.png)

**Comment by Bastijn** [comment]
I was not able to reproduce this bug. When I use this function in G-DASH it ends up using the 'createpass' function as described here: https://github.com/Bastijn/g-dash/blob/6fc47ccb5089fc6b595710f8b12ccae99757dfc0/ajax/walletactions.php#L18 which does not do anything with the wallet.dat except for encrypting it. Do you have any additional information?
