### ISSUE TITLE
Incorrect link in the Node page

### ISSUE THREAD

**Issue by si2w** [Bastijn/g-dash#3]
The link shown when there are no incoming connections is incorrect.

![75v2ihb - imgur](https://user-images.githubusercontent.com/2494268/35334731-996925f2-0113-11e8-8a92-8223e526f393.png)

It should be https://dev.gulden.com/contribute/#nodes instead of https://developer.gulden.com/nodes/ 

https://developer.gulden.com/nodes/ exists but returns an SSL certificate error : 
![3jd6d5v](https://user-images.githubusercontent.com/2494268/35334878-196cb692-0114-11e8-9a2c-fdfb92f1b264.png)

**Comment by Bastijn** [comment]
Fixed in version 0.23
