### ISSUE TITLE
Remove GT as rate provider

### ISSUE THREAD

**Issue by achterhooker** [Bastijn/g-dash#30]
In settings you can select GuldenTrader as rate provider. Since they are shutting down services this option can be removed

**Comment by timkoers** [comment]
The same applies for Nocks.

**Comment by Bastijn** [comment]
Removed Nocks and GT in G-DASH V1.4 (https://github.com/Bastijn/g-dash/commit/87f40151e4c70d9b3154cfb1fbfe9b4e90afe7d6)
