### ISSUE TITLE
Add command line command to test remote access

### ISSUE THREAD

**Issue by si2w** [Bastijn/g-dash#4]
It could nice to add this command to test the access to the P2P port form the outside in the node page in case there are no incoming connection : 
For example : 
`telnet _ip_ 9231` if it doesn't fail then its listening

**Comment by Bastijn** [comment]
This functionality is already implemented in Settings --> Config Check. See [this section](https://github.com/Bastijn/g-dash/blob/64cbfb53f11dececdc86520d332374672acaecfe/configcheck.php#L80) for more information.
