### ISSUE TITLE
Replace md5/sha1 by bcrypt or PBKDF2

### ISSUE THREAD

**Issue by si2w** [Bastijn/g-dash#5]
In lib/functions/functions.php and settings.php, the hash function used is an md5 of a sha1 applied on the password. Both are insecure and broken.
 
Bcrypt and PBKDF2 are two good replacement for md5/sha1 who were broken.

**Comment by Bastijn** [comment]
I agree this would be an security enhancement. A transition script will be needed where the passwords are updated to the new encryption.

**Comment by Bastijn** [comment]
Fixed in version 0.23
