### ISSUE TITLE
Add IPv6 port check to config check

### ISSUE THREAD

**Issue by Bastijn** [Bastijn/g-dash#6]
The configuration check for open ports currently only works for IPv4 addresses. Add IPv6 support by supplying the address with brackets (i.e. [::1]).

**Comment by tripledm** [comment]
I am glad Bastijn reported this so that Bastijn can assign this enhancement to the task list as I noticed as well that only IPv4 and not IPv6 detected in full node port forward ;-)

**Comment by Bastijn** [comment]
Fixed in https://github.com/Bastijn/g-dash/commit/5c4c436b0133857a27dfbd78b051ad7a27c34d1e
