### ISSUE TITLE
Reading the tail of a large log file

### ISSUE THREAD

**Issue by DubMatrix** [Bastijn/g-dash#8]
The debug.log file was about 240Mb in size and when using the `showlog` command, I got an error stating:

[AJAX] Invalid JSON - Server responded:
**Fatal error**:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 212209296 bytes) in **/var/www/html/lib/terminal/rpc_commands.php** on line **33**

Suggestion is to check out [this](https://stackoverflow.com/questions/15025875/what-is-the-best-way-in-php-to-read-last-lines-from-a-file) post and possibly use [this](https://gist.github.com/lorenzos/1711e81a9162320fde20) for a solution.

**Comment by mjmacleod** [comment]
An alternative might be something like logrotate

**Comment by Bastijn** [comment]
As Malcolm suggested this is something that could be added to your system using logrotate.
